### PR TITLE
unsupports certain interpreters and file types

### PR DESCRIPTION
**Pull request by kzidane**
@dmalan, do we want something like this? Is it worth looking for a shebang too?

cc @glennholloway

### CODE REVIEW

**Comment by dmalan** [comment]
That'd be good, unless is there a magic number we can just check for among the first bytes of a binary outputted by `clang` and `gcc`?

**Comment by kzidane** [comment]
@dmalan, `file "$1" | grep -o executable`?

> The type printed will usually contain one of the words text (the file contains only printing characters and a few common control characters and is probably safe to read on an ASCII terminal), **executable (the file contains the result of compiling a program in a form understandable to some UNIX kernel or another)**, or data meaning anything else (data is usually “binary” or non-printable).

See [man file](https://linux.die.net/man/1/file)! Should we keep looking for a more specific solution?

**Comment by kzidane** [comment]
PS: Recall you wanted to detect some interpreters per that Asana? This is primarily why I took the proposed approach.

**Comment by dmalan** [comment]
Sounds promising. Though for our sake, feels ideal to support only those files with which `debug50` can actually be useful. Is there some way to check a binary for whether it's been compiled with debugging symbols (`-ggdb`)?

**Comment by kzidane** [comment]
@dmalan, how does fa637be look? Screencast: [unsupported.zip](https://github.com/cs50/harvard.cs50.debug/files/570554/unsupported.zip)

**Comment by kzidane** [comment]
@dmalan, see 9872533! Any other takes?

**Pull request merged**
