### PR TITLE
rewrites debug50 when deleted

### PR DESCRIPTION
**Pull request by kzidane**
@glennholloway, any takes?

cc @dmalan

### CODE REVIEW

**Comment by kzidane** [comment]
Relevant: cs50/ide50#25

**Comment by glennholloway** [comment]
@kzidane: The way this is written, there appears to be one watcher for the whole system, which is capable of watching multiple paths. If the file at any of those paths disappears, then all of the registered "delete handlers" are called with the path of the file as part of the event argument (`e`). If one of the delete handlers recognizes that path, it does its thing. (In our case, that means restoring the file and re-registering the path to be watched for deletion.)

Is that an accurate enough model of what's going on?

In the following lines, would it make any difference if the argument to `writeDebug50` were just `null`?
I.e., does `watchDebug50` need to be invoked again after the deleted script has been restored?

    // write debug50 when deleted
    watcher.once("delete", function(e) {
        if (e.path === path)
            writeDebug50(watchDebug50);
    });

**Comment by kzidane** [comment]
@glennholloway,

> Is that an accurate enough model of what's going on?

Right on! :-)

> In the following lines, would it make any difference if the argument to `writeDebug50` were just null?
> I.e., does `watchDebug50` need to be invoked again after the deleted script has been restored?

By [`watcher.watch(path)`](https://github.com/cs50/harvard.cs50.debug/blob/fb6f0ff24480ffe220443fd356e9fc0602c78136/debug.js#L344), we register for watching the file at `path` (in our case `debug50`). When the file gets deleted, it's automatically [unregistered](https://github.com/c9/core/blob/master/plugins/c9.ide.watcher/watcher.js#L214) by C9's watcher plugin, so we need to register it for watching again, after rewriting.

Instead of [passing](https://github.com/cs50/harvard.cs50.debug/blob/fb6f0ff24480ffe220443fd356e9fc0602c78136/debug.js#L349) `watchDebug50` which does both, registering `debug50` for watching and setting up an event handler, we could pass a callback that would just register `debug50` again for watching (without setting up an event handler), but it felt cleaner and slightly more succinct to do it that way?

The caveat is that [`watcher.once`](https://github.com/cs50/harvard.cs50.debug/blob/fb6f0ff24480ffe220443fd356e9fc0602c78136/debug.js#L347) deletes the handler after it's been executed once. This prevents registering multiple handlers when calling `watchDebug50` as a callback after `debug50`'s been deleted after being re-written at least once.

**Comment by glennholloway** [comment]
@kzidane: Thanks for the amplification. This sounds good. Let's ship it and hope that we can catch the pending deployment that you mentioned.

**Pull request merged**
