### PR TITLE
simplify gui of terminal debugger

### PR DESCRIPTION
**Pull request by kzidane**
@dmalan that's what you want? any comments?

Screenshots:
debug-light
debug-light-running
debug-light-enabled-argv-while-stopped
debug-light-disabled-argv-while-running

debug-dark
debug-dark-running
debug-dark-enabled-argv-while-stopped
debug-dark-disabled-argv-while-running

### CODE REVIEW

**Comment by dmalan** [comment]
Let's remove mention of `argv` altogether and shift the actual command and
command-line args to the left? If the command is run as `debug50 foo bar
baz`, can we display `foo bar baz` instead of `/path/to/foo bar baz`?

**Comment by kzidane** [comment]
@dmalan `argv` removed. guess I can alter /path/to/foo with foo, but wouldn't that be a bit misleading since `argv[0]` is actually the full path?

**Comment by dmalan** [comment]
Depends. Is the runner running gdb on the program by its full path? Can we
avoid by having it use a relative path and a $CWD?

**Comment by kzidane** [comment]
yes, full path. not sure if relative is possible. will try to figure out!

**Comment by dmalan** [comment]
nbd if not easily possible. Hopefully `debug50` will obviate the need for
students to ever see that tab.

**Comment by kzidane** [comment]
umm, recall debugger50 with -o leverages C9's existing run/debug system. in
fact, I opened this tab through debugger50. likely-to-be-removed feature?

**Comment by dmalan** [comment]
I assume so eventually, if only because it doesn't (I don't think) add
much.

**Comment by kzidane** [comment]
Closing as we no longer use the standard run and debug system by default!

**Pull request closed without merging**
